services:
  scan:
    build: .
    image: danilsidorov/scan:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/public/uploads
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scan.rule=Host(`scans.omnaris.xyz`)"
      - "traefik.http.routers.scan.entrypoints=websecure"
      - "traefik.http.routers.scan.tls.certresolver=myresolver"
      - "traefik.http.services.scan.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command:
      - "--label-enable"
      - "--interval=30"
      - "--rolling-restart"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true